"""
Django settings for freshfood project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w!^w0ta%bio4c%fh_*c^f=v**c11q&6devz2i@3)s+=$h9hr5i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Security Settings
# https://docs.djangoproject.com/en/6.0/topics/security/

if DEBUG :
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False

else:
    SECURE_SSL_REDIRECT = True
    # Session and CSRF cookies should be secure
    SESSION_COOKIE_SECURE = True
    # CSRF cookie should be secure
    CSRF_COOKIE_SECURE = True
    # Prevent the browser from guessing content types
    SECURE_CONTENT_TYPE_NOSNIFF = True
    # Prevent clickjacking
    X_FRAME_OPTIONS = 'DENY'
    # Enable the XSS filter in the browser
    SECURE_BROWSER_XSS_FILTER = True
    # Use HSTS to force HTTPS
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # 60 seconds for testing; increase to a higher value like 31536000 for production
    SECURE_HSTS_PRELOAD = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True

    # Content Security Policy (CSP) Settings
    CSP_USE_NONCE = True
    # Define CSP directives
    CSP_DEFAULT_SRC = ("'self'",)    
    # Define other CSP directives as needed
    CSP_CONNECT_SRC = ("'self'",) 
    # Define other CSP directives as needed
    CSP_FRAME_SRC = ("'self'",)  
    CSP_BASE_URI = ("'self'",) 
    CSP_FORM_ACTION = ("'self'",)
    CSP_MEDIA_SRC = ("'self'",) 
    CSP_OBJECT_SRC = ("'none'",)
    CSP_CHILD_SRC = ("'self'",) 
    CSP_FONT_SRC = ("'self'",) 
    CSP_MANIFEST_SRC = ("'self'",)
    CSP_WORKER_SRC = ("'self'",) 
    CSP_PREFETCH_SRC = ("'self'",)
    CSP_BLOCK_ALL_MIXED_CONTENT = True
    CSP_UPGRADE_INSECURE_REQUESTS = True
    CSP_SCRIPT_SRC = ("'self'",) 
    CSP_STYLE_SRC = ("'self'", "'unsafe-inline'",) 
    CSP_IMG_SRC = ("'self'", "data:", "*")
    CSP_FONT_SRC = ("'self'",)

ALLOWED_HOSTS = [ '192.168.225.190', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'food_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'freshfood.urls'
#AUTH_USER_MODEL = 'account.CustomUser'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'freshfood.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles_root'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
    # Ajoutez d'autres chemins si vous avez des fichiers statiques globaux
]

# Si vous utilisez des fichiers média (téléchargements utilisateurs)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'