# Generated by Django 5.2.5 on 2025-12-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0002_product_categorie_alter_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
