# Generated by Django 5.2.5 on 2025-12-15 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0003_order_client_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
